language: cpp
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Hs4uOpT5baqvud5Is0TShPzulK/DNsa8WkebyaIPsENT7q4+KGPYaVj9W0p8pWscp0xKWogzKjwmmfpWU7LJEtplXk1GLzSW9l7PoKmvN3dpWN5tvHdX5laHsudDrSlU/+62S4zq6t0FpiLGhmOp0bjffKeSSxprpTE9OwZyecaM12ADnNT1D+pPYe18jGC05Bs9R5Idt1oJq2N1Z+XYok5VdUML7O0qSBf/zq2IY0L+UhtGE056oSMe0st0gfLv0iN845SaNaY+F9GBZZlaEo0wKkqzpfqjjqMsQ96z+iWiovVkL07klmdiy7tbz8dOkpBjPaMDP9oYsKkhx/8HZWOYFelDJsUdOgdNkkSxMnq7H774TFplVU4mNn+nt4EFMN4IGjZzeoWuX6+3Ut/ew5h3v9dEiH9TF03bc5kzpEM+sBg9z1654PUOQGzPRaQXRqLuEFcj+O4jEdF1mAqvOwDg9fihY3P4c6SVaLTu0HfERT0nU9BDaRTAnOQVW3768oPR2WSSpYrG1MR1kHS6U8ODTkGAitbdmBJKorGzIfbjJW3XS5OVOnkodfMKJAt2qhG/8RY+vGpy5GJwJZMArigt4bXlvLNizCTSFhK3WYjxL/hqUrOWg7n1Jz4sHcOyXJ8jfTW1elO5KZweJbqpJibtGkOVE8KCtcOBJwQmU/4="

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler:
          - clang
          - g++
      addons:
        apt:
          sources:
            #- llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            #- clang-3.8
            - g++
            - cmake

        coverity_scan:
          # GitHub project metadata
          # ** specific to your project **
          project:
              name: openscenegraph/osg
              description: OpenSceneGraph
              version: 3.5.x
          # Where email notification of build analysis results will be sent
          notification_email: robert@openscenegraph.com
          # Commands to prepare for build_command
          # ** likely specific to your build **
          build_command_prepend: cmake -DCMAKE_BUILD_TYPE=Release -DOSG_USE_AGGRESSIVE_WARNINGS=0 .
          # The command that will be added as an argument to "cov-build" to compile your project for analysis,
          # ** likely specific to your build **
          build_command: make -j 3
          # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
          # Take care in resource usage, and consider the build frequency allowances per
          #   https://scan.coverity.com/faq#frequency
          branch_pattern: coverity_scan

    # OSX build
    - os: osx

# script:
#    - mkdir build
#    - cd build
#    - travis_wait 60 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../product -DBUILD_OSG_EXAMPLES=ON ..
#    - make install -j 3

script:
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mkdir build && cd build && travis_wait 60 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../product -DBUILD_OSG_EXAMPLES=ON ../ && make -j3 ; fi
